[tool.poetry]
name = "visualize"
version = "0.1.0"
description = ""
authors = ["ziyi xi <ziyixi@mail.ustc.edu.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pygmt = "^0.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
